Repository dimsav/laravel-translatable, pull requests merged in 2018-08, with the labels that each got.

#508 Allow to change default translation model namespace from config file
  src/Translatable/Translatable.php
  src/config/translatable.php
  tests/TranslatableTest.php
Labels: feature

#509 release preparation for v9.1.0
  changelog.md
Labels: documentation, next release

#511 run composer self-update as sudo
  .circleci/config.yml
Labels: bug
